class Weather {
  String dayOfTheWeek;
  String dateMonth;
  String imgWeatherStates;
  int temperature;
  String weatherStates;
  String dateMonthYear;
  int humidity;
  int predictability;

  Weather({
    required this.dayOfTheWeek,
    required this.dateMonth,
    required this.imgWeatherStates,
    required this.temperature,
    required this.weatherStates,
    required this.dateMonthYear,
    required this.humidity,
    required this.predictability,
  });
}

List<Weather> weathers = [
  Weather(
      dayOfTheWeek: 'Mon',
      dateMonth: '8/02',
      imgWeatherStates: 'assets/images/showers.png',
      temperature: -10,
      weatherStates: 'Snow',
      dateMonthYear: 'Mon Aug 2, 2021',
      humidity: 10,
      predictability: 10),
  Weather(
      dayOfTheWeek: 'Tue',
      dateMonth: '8/03',
      imgWeatherStates: 'assets/images/sleet.png',
      temperature: -15,
      weatherStates: 'Sleet',
      dateMonthYear: 'Tue Aug 3, 2021',
      humidity: 10,
      predictability: 10),
  Weather(
      dayOfTheWeek: 'Web',
      dateMonth: '8/04',
      imgWeatherStates: 'assets/images/heavyCloud.jpeg',
      temperature: 37,
      weatherStates: 'Light Cloud',
      dateMonthYear: 'Web Aug 4, 2021',
      humidity: 45,
      predictability: 20),
  Weather(
      dayOfTheWeek: 'Thu',
      dateMonth: '8/05',
      imgWeatherStates: 'assets/images/heavyCloud.jpeg',
      temperature: 37,
      weatherStates: 'Light Cloud',
      dateMonthYear: 'Thu Aug 5, 2021',
      humidity: 45,
      predictability: 20),
  Weather(
      dayOfTheWeek: 'Fri',
      dateMonth: '8/06',
      imgWeatherStates: 'assets/images/heavyCloud.jpeg',
      temperature: 37,
      weatherStates: 'Light Cloud',
      dateMonthYear: 'Fri Aug 6, 2021',
      humidity: 45,
      predictability: 20),
  Weather(
      dayOfTheWeek: 'Sat',
      dateMonth: '8/07',
      imgWeatherStates: 'assets/images/showers.png',
      temperature: -10,
      weatherStates: 'Snow',
      dateMonthYear: 'Sat Aug 7, 2021',
      humidity: 10,
      predictability: 10),
  Weather(
      dayOfTheWeek: 'Sun',
      dateMonth: '8/08',
      imgWeatherStates: 'assets/images/showers.png',
      temperature: -10,
      weatherStates: 'Snow',
      dateMonthYear: 'Sun Aug 8, 2021',
      humidity: 10,
      predictability: 10),
  Weather(
    dayOfTheWeek: 'Today',
    dateMonth: '8/09',
    imgWeatherStates: 'assets/images/showers.png',
    temperature: 37,
    weatherStates: 'Light Cloud',
    dateMonthYear: 'Mon Aug 9, 2021',
    humidity: 45,
    predictability: 20,
  ),
  Weather(
      dayOfTheWeek: 'Tue',
      dateMonth: '8/10',
      imgWeatherStates: 'assets/images/sleet.png',
      temperature: -15,
      weatherStates: 'Sleet',
      dateMonthYear: 'Tue Aug 10, 2021',
      humidity: 30,
      predictability: 10),
  Weather(
      dayOfTheWeek: 'Web',
      dateMonth: '8/11',
      imgWeatherStates: 'assets/images/showers.png',
      temperature: -10,
      weatherStates: 'Snow',
      dateMonthYear: 'Web Aug 11, 2021',
      humidity: 10,
      predictability: 30),
  Weather(
      dayOfTheWeek: 'Thu',
      dateMonth: '8/12',
      imgWeatherStates: 'assets/images/showers.png',
      temperature: -10,
      weatherStates: 'Snow',
      dateMonthYear: 'Thu Aug 12, 2021',
      humidity: 10,
      predictability: 10),
  Weather(
      dayOfTheWeek: 'Fri',
      dateMonth: '8/13',
      imgWeatherStates: 'assets/images/showers.png',
      temperature: -10,
      weatherStates: 'Snow',
      dateMonthYear: 'Fri Aug 13, 2021',
      humidity: 10,
      predictability: 10),
  Weather(
      dayOfTheWeek: 'Sat',
      dateMonth: '8/14',
      imgWeatherStates: 'assets/images/showers.png',
      temperature: -10,
      weatherStates: 'Snow',
      dateMonthYear: 'Sat Aug 14, 2021',
      humidity: 10,
      predictability: 10),
  Weather(
      dayOfTheWeek: 'Sun',
      dateMonth: '8/15',
      imgWeatherStates: 'assets/images/sleet.png',
      temperature: -15,
      weatherStates: 'Sleet',
      dateMonthYear: 'Sun Aug 15, 2021',
      humidity: 10,
      predictability: 10),
  Weather(
      dayOfTheWeek: 'Mon',
      dateMonth: '8/16',
      imgWeatherStates: 'assets/images/sleet.png',
      temperature: -15,
      weatherStates: 'Sleet',
      dateMonthYear: 'Mon Aug 16, 2021',
      humidity: 10,
      predictability: 10),
  Weather(
      dayOfTheWeek: 'Tue',
      dateMonth: '8/17',
      imgWeatherStates: 'assets/images/heavyCloud.jpeg',
      temperature: 37,
      weatherStates: 'Light Cloud',
      dateMonthYear: 'Tue Aug 17, 2021',
      humidity: 45,
      predictability: 20),
  Weather(
      dayOfTheWeek: 'Web',
      dateMonth: '8/18',
      imgWeatherStates: 'assets/images/showers.png',
      temperature: -10,
      weatherStates: 'Snow',
      dateMonthYear: 'Web Aug 18, 2021',
      humidity: 10,
      predictability: 10),
  Weather(
      dayOfTheWeek: 'Thu',
      dateMonth: '8/19',
      imgWeatherStates: 'assets/images/sleet.png',
      temperature: -15,
      weatherStates: 'Sleet',
      dateMonthYear: 'Thu Aug 19, 2021',
      humidity: 10,
      predictability: 10),
  Weather(
      dayOfTheWeek: 'Fri',
      dateMonth: '8/20',
      imgWeatherStates: 'assets/images/showers.png',
      temperature: -10,
      weatherStates: 'Snow',
      dateMonthYear: 'Fri Aug 20, 2021',
      humidity: 10,
      predictability: 10),
  Weather(
      dayOfTheWeek: 'Sat',
      dateMonth: '8/21',
      imgWeatherStates: 'assets/images/sleet.png',
      temperature: -15,
      weatherStates: 'Sleet',
      dateMonthYear: 'Sat Aug 21, 2021',
      humidity: 10,
      predictability: 10),
  Weather(
      dayOfTheWeek: 'Sun',
      dateMonth: '8/22',
      imgWeatherStates: 'assets/images/heavyCloud.jpeg',
      temperature: 37,
      weatherStates: 'Light Cloud',
      dateMonthYear: 'Sun Aug 22, 2021',
      humidity: 45,
      predictability: 20),
];
